### PR TITLE
Add past events to the website

### PR DESCRIPTION
**Pull request by stuartlangridge**
This PR adds past versions of the conf.techmids.io website to the current website, so that people can get access to the pages for past events to see who spoke at them, what they spoke about, and so on. Most conferences have this, and it's a very useful historical record. The goal here is that making sure that past versions of the conference are made available with close to zero burden on the website maintainers. The PR comes in three parts.

# Part 1

(The two "add past version of website" commits)

The websites for the October 2022 and June 2023 events. These websites are pure static HTML with no outside dependencies and no build process; each is an independent folder of static HTML/CSS/JS stored in `public/past`. This is done so that they are self-contained; changes to the build process of the current website will not affect these past websites at all, because they've already been built to static HTML; they are not rebuilt on each change. This means that changing the version of next.js (or changing away from next.js entirely) and the like will not stop these past versions from working.

# Part 2

(The "link-to-the-past" commit)

A script which _generates_ these static versions of the website, which is called `link-to-the-past`. It is documented in detail in `link-to-the-past/README.md`, but the basic idea is this: there will be a day when the October 2023 event (for example) is over and you want to start changing the website for a 2024 event. On that day, before you make any changes to refer to the 2024 website, run `npm run link-to-the-past 2023-10`. This will bundle up the website as it currently looks into a static version of itself at `past/2023-10`. Then go ahead and make whatever changes are deemed necessary. This script is all inside the `link-to-the-past` folder, and is pure command-line nodejs; it doesn't run servers or anything like that, and you only run it once to create the static version, not every time.

# Part 3

(The "Simple past-events page" commit)

A `/past-events` page on the website itself, linked from the footer. This page is built at build-time and adds a simple link to each of the past events by inspecting the filesystem. This is next.js stuff, and it is entirely possible that someone more expert with next.js itself could do this a more efficient or elegant way, and if that person exists and has the time then I would be happy to have them do this instead.

### CODE REVIEW

**Comment by stuartlangridge** [comment]
(note that the Past Events page could do with attention from a designer of some kind, which is not me. But that probably isn't a blocker.)

**Comment by Waterdrips** [comment]
Lots of the images are not loading (looking at the preview link)

Could we bundle the images from the site at build time into the same folder and change any img links to be a child of the folder?



I'll take a look at a design for the past events page once this goes live

**Comment by mattandrews** [comment]
I get this locally when trying to run `npm run link-to-the-past 2023-10` (and `node link-to-the-past/link-to-the-past.mjs` too):

```
> node link-to-the-past/link-to-the-past.mjs
file:///Users/matt/Dev/sil/conf.techmids.io/link-to-the-past/paths.mjs:13
        throw new Error(
              ^

Error: Expected to find the next config in /Users/matt/Dev/sil/conf.techmids.io/next.config.js, but we didn't.
This isn't supposed to happen, and is a bug in this script.
    at get_paths (file:///Users/matt/Dev/sil/conf.techmids.io/link-to-the-past/paths.mjs:13:15)
    at main (file:///Users/matt/Dev/sil/conf.techmids.io/link-to-the-past/link-to-the-past.mjs:16:25)
    at file:///Users/matt/Dev/sil/conf.techmids.io/link-to-the-past/link-to-the-past.mjs:36:1
```

**Comment by stuartlangridge** [comment]
> Lots of the images are not loading (looking at the preview link)
> 
> Could we bundle the images from the site at build time into the same folder and change any img links to be a child of the folder?

Huh, I hadn't noticed the logo images, good catch. The issue there is that the images _are_ bundled into the folder (https://conf-techmids-io-git-fork-stuartlangridge-main-tech-mids.vercel.app/past/2022-10/fusion-events.png exists, for example), but that the img link in the page wasn't updated to make it a relative link when `next` made the static build. What I think is best to do there is to manually patch the image links in the static build for that bundled static site, and I have now added this to the PR.

**Comment by stuartlangridge** [comment]
> The `next.config.js` file it references _does_ exist...

Well, that's not supposed to happen (just like it says :)) Sorry about that @mattandrews -- I don't know what's causing the problem, but I have at least poked the script to relate what the error actually _is_ when that happens so at least we can see what's up. Can you run it again?

**Comment by mattandrews** [comment]
Done! Got this:

```
(The actual error we got was this: TypeError: Cannot read properties of undefined (reading 'R_OK'))
```

**Comment by Waterdrips** [comment]
> > Lots of the images are not loading (looking at the preview link)
> > 
> > Could we bundle the images from the site at build time into the same folder and change any img links to be a child of the folder?
> 
> Huh, I hadn't noticed the logo images, good catch @Waterdrips. The issue there is that the images _are_ bundled into the folder (https://conf-techmids-io-git-fork-stuartlangridge-main-tech-mids.vercel.app/past/2022-10/fusion-events.png exists, for example), but that the img link in the page wasn't updated to make it a relative link when `next` made the static build. What I think is best to do there is to manually patch the image links in the static build for that bundled static site, and I have now added this to the PR.
> 

You may be able to specify a base path on build?

**Comment by stuartlangridge** [comment]
@mattandrews what? how can that not work? What does `node -e 'console.log(require("node:fs/promises").constants.R_OK)'` say?

**Comment by mattandrews** [comment]
Same thing: `TypeError: Cannot read properties of undefined (reading 'R_OK')` – some random comment here suggests it got deprecated? https://github.com/nodejs/node/issues/8044

I'm on Mac in case that adds anything...

**Comment by mattandrews** [comment]
```
> node -e 'console.log(require("node:fs").constants.R_OK)'
4
```

... `promises` might be your issue here

**Comment by stuartlangridge** [comment]
> You may be able to specify a base path on build?

I _do_ specify a base path on build :-) Most of the links to things do indeed get patched up, but those image links don't. I don't know why; someone who knows more about next.js may do. However, the advantage with dumping the sites to static is that we don't actually have to work this out immediately; it's OK to patch up the static HTML to make it work like I did, because then it stays fixed. A patch to make next.js better about fixing up such image links in the future when it exports to static would be a useful thing for someone to work on at some point if it becomes annoying, though. It looks like the image links are fixed in the vercel preview now, anyway, as expected, so that's good.

**Comment by stuartlangridge** [comment]
> ... `promises` might be your issue here

weird, I don't get why it still works here, since it seems to have been dropped yonks ago. Anyway, PR updated to get the stuff from just `fs` and that should work now, I think. Thank you!

**Comment by mattandrews** [comment]
```
Backing up the next.config.js before we fiddle with it...
Written our custom link-to-the-past config
Moving the 'past' folder out of the way, from /Users/matt/Dev/sil/conf.techmids.io/public/past to /Users/matt/Dev/sil/conf.techmids.io/link-to-the-past/temp_past
Confirming that we can write to the output directory /Users/matt/Dev/sil/conf.techmids.io/link-to-the-past/export
There was an error, sorry.
I am attempting to restore things after the error.
Moving the 'past' folder back, from /Users/matt/Dev/sil/conf.techmids.io/link-to-the-past/temp_past back to /Users/matt/Dev/sil/conf.techmids.io/public/past
I shall now abort. The error in the script was this:
Error: We cannot write to /Users/matt/Dev/sil/conf.techmids.io/link-to-the-past/export. This is not supposed to happen, and is a bug in this script.
    at assure_output_dir (file:///Users/matt/Dev/sil/conf.techmids.io/link-to-the-past/make-changes.mjs:38:19)
    at main (file:///Users/matt/Dev/sil/conf.techmids.io/link-to-the-past/link-to-the-past.mjs:23:15)
```

Export directory exists and I just made it 777 (and tried running the script as sudo), same error... sorry!

(LOVED the ascii art!)

**Comment by stuartlangridge** [comment]
> same error... sorry!

...for the same reason. I have, _this_ time, checked that there's nowhere else I'm using fs.constants too :)

**Comment by mattandrews** [comment]
It did things for a while, then:

```
Error occurred prerendering page "/past-events". Read more: https://nextjs.org/docs/messages/prerender-error
Error: ENOENT: no such file or directory, scandir '/Users/matt/Dev/sil/conf.techmids.io/public/past'
info  - Generating static pages (11/11)

> Export encountered errors on following paths:
	/past-events
There was an error, sorry.
I am attempting to restore things after the error.
Moving the 'past' folder back, from /Users/matt/Dev/sil/conf.techmids.io/link-to-the-past/temp_past back to /Users/matt/Dev/sil/conf.techmids.io/public/past
I shall now abort. The error in the script was this:
undefined
```

**Comment by mattandrews** [comment]
Haha thanks for all the effort, I can see how much work's gone into this. Thank you!

**Comment by Waterdrips** [comment]
image

https://conf-techmids-maxlckqug-tech-mids.vercel.app/past/2022-10/speakers/mark-perkin.html

each user page has a set of sponsors too.

We can probably get away with merging this and fixing up if it becomes an issue later?

**Pull request merged**
